services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: laravel11-app
    volumes:
      - .:/workspaces/${COMPOSE_PROJECT_NAME:-laravel11}
    working_dir: /workspace
    command: bash -lc "tail -f /dev/null"
    environment:
      - TZ=UTC
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=admin
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
      - mailpit

  db:
    image: postgres:15
    container_name: laravel11-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: admin
    volumes:
      - dbdata-laravel11-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: laravel11-redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: laravel11-mailpit
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP

volumes:
  dbdata-laravel11-postgres:
